# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

# Model Arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelTorchTuneCheckpointer
  checkpoint_dir: /home/andrewor/local/logs/tune/c4-llama-qat
  checkpoint_files: [
    meta_model_0-8da4w-qat.pt
  ]
  recipe_checkpoint: null
  output_dir: /home/andrewor/local/logs/tune/c4-llama-qat
  model_type: LLAMA3

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Meta-Llama-3-8B-Instruct/original/tokenizer.model

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["hellaswag", "wikitext"]
limit: null
max_seq_length: 8192
batch_size: 8

# Quantization specific args
quantizer: null
#quantizer:
#  _component_: torchtune.utils.quantization.Int8DynActInt4WeightQuantizer
#  groupsize: 256
