model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /home/andrewor/local/logs/tune/c4-llama-qat
  checkpoint_files: [
    meta_model_0.pt
  ]
  recipe_checkpoint: null
  output_dir: /home/andrewor/local/logs/tune/c4-llama-qat
  model_type: LLAMA3

device: cuda
dtype: bf16
seed: 1234

quantizer:
  _component_: torchtune.utils.quantization.Int8DynActInt4WeightQATQuantizer
  groupsize: 256
